services:
  db:
    image: ankane/pgvector:latest
    container_name: memoria-db
    restart: always
    environment:
      - POSTGRES_DB=memoria
      - POSTGRES_USER=kowshik
      - POSTGRES_PASSWORD=memoria123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
